apiVersion: apps/v1
kind: Deployment
metadata:
  name: flurly
  labels:
    app: flurly
spec:
  replicas: 1

  # match pods by their labels in order to scale
  selector:
    matchLabels:
      app: flurly

  # template for the pods crated with this Deployment
  template:
    metadata:
      labels:
        app: flurly

    spec:
      containers:
      - name: flurly

        # change the container image to run, when pulling from another registry
        image: florinzz/flurly:latest
        #image: localhost:5000/flurly:latest

        # always pull the image when we are testing new images on same tags
        imagePullPolicy: Always

        # application exposes port 3000
        ports:
        - containerPort: 3000

        # define a probe that checks if the application is still running
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 1

        # define a probe to check if the application has started up
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 1

        # define resource requests and limits
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi